### PR TITLE
Refactor imap modules

### PR DESCRIPTION
**Pull request by zevaverbach**
Quite a lot of changes here.  The commits tell the story, but the general effort is to put everything into functions and classes so they can be tested.  I also improved parsing of the email body to capture the desired fields, though this still needs more work.  (see the Email model)

### CODE REVIEW

**Comment by zevav** [comment]
@cssidy to be clear, I'll leave it to you to merge/reject the pull request.  It's your baby, so I wouldn't feel comfortable merging all this.

**Comment by cssidy** [comment]
For the test and test directory....

Hmm, it did not pass for me. It says:

line 1, in <module>
    from _config import config_dict
ImportError: No module named '_config'

I have a _config.py file with a variable dictionary called config_dict in it. And at the top of my test page, from _config import config_dict.

**Comment by zevav** [comment]
@cssidy it's odd, but an `__init__.py` that I put in the tests/ folder isn't showing up in this branch.  Can you add one locally and see if your test runs then?

**Comment by zevav** [comment]
Sorry @cssidy, please try with the latest version of this branch.  I had accidentally .gitignored the __init__.py I created in the tests/ dir.  It should run now.  Let me know!

**Comment by cssidy** [comment]
Ar, I am so confused with the GitHub platform, I just hit a button that approved all of the changes of the pull request to the master, but what I meants was to approve the .gitignore/init.py changes you just mentioned. Oops

**Comment by cssidy** [comment]
Where do I see what goes in the __init__.py file?

**Comment by zevav** [comment]
Just pull the latest version of the branch, and the __init__.py file will
be there; it's blank.

You should be able to undo your approval.  You don't have to approve the
changes I made, only merge the pull request once it's in the shape you want
it to be.

Zev Averbach
Averbach Transcription
(212) 729-4850
www.avtranscription.com

**Pull request closed without merging**
